apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { { include "ctf-rs.fullname" . } }
  labels: { { include "ctf-rs.labels" . | nindent 4 } }
  annotations: { { toYaml . | nindent 4 } }
spec:
  ingressClassName: { { . } }
  tls:
    - hosts:
        - { { . | quote } }
      secretName: { { .secretName } }
  rules:
    - host: { { .host | quote } }
      http:
        paths:
          - path: { { .path } }
            pathType: { { . } }
            backend:
              service:
                name: { { include "ctf-rs.fullname" $ } }
                port:
                  number: { { $.Values.service.port } }
