apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: operator
  labels:
    app: ctf-rs
    component: operator
    scope: backend
  annotations: { { toYaml . | nindent 4 } }
automountServiceAccountToken: { { .Values.serviceAccount.automount } }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server
  namespace: ctf
  labels:
    app: ctf-rs
    component: api
    scope: user
  annotations: { { toYaml . | nindent 4 } }
automountServiceAccountToken: { { .Values.serviceAccount.automount } }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server-admin
  namespace: ctf
  labels:
    app: ctf-rs
    component: api
    scope: admin
  annotations: { { toYaml . | nindent 4 } }
automountServiceAccountToken: { { .Values.serviceAccount.automount } }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: challenges
  namespace: ctf
  labels:
    app: ctf-rs
    component: api
    scope: user
  annotations: { { toYaml . | nindent 4 } }
automountServiceAccountToken: { { .Values.serviceAccount.automount } }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: verifier
  namespace: ctf
  labels:
    app: ctf-rs
    component: api
    scope: user
  annotations: { { toYaml . | nindent 4 } }
automountServiceAccountToken: { { .Values.serviceAccount.automount } }
