apiVersion: v1
kind: Service
metadata:
  name: operator
  labels:
    app: ctf-rs
    component: operator
    scope: backend
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector: { { include "ctf-rs.selectorLabels" . | nindent 4 } }
  internalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app: ctf-rs
    component: api
    scope: user
spec:
  type: { { .Values.api.service.user.type } }
  ports:
    - port: { { .Values.api.service.user.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ctf-rs
    component: api
    scope: user
  internalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: api-admin
  labels:
    app: ctf-rs
    component: api
    scope: admin
spec:
  type: { { .Values.api.service.admin.type } }
  ports:
    - port: { { .Values.api.service.admin.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ctf-rs
    component: api
    scope: admin
  internalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: verifier
  namespace: ctf-backend
  labels:
    app: ctf-rs
    component: verifier
    scope: backend
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector: { { include "ctf-rs.selectorLabels" . | nindent 4 } }
  internalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: challenge
  namespace: ctf
  labels:
    app: ctf-rs
    component: challenge
    scope: user
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector: { { include "ctf-rs.selectorLabels" . | nindent 4 } }
  internalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: ctfdb
  namespace: ctf-backend
  labels:
    app: ctf-rs
    component: challenge
    scope: user
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector: { { include "ctf-rs.selectorLabels" . | nindent 4 } }
  internalTrafficPolicy: Local
